const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];

/* -------------------------------------------------------
   HERO FRAME SEQUENCE
   87 WebP frames, driven directly by hero scroll progress.
   ------------------------------------------------------- */
const hero=$('#hero');
const heroCanvas=$('#heroCanvas');
const heroContext=heroCanvas?.getContext('2d',{alpha:false});
const heroPlaceholder=$('#heroPlaceholder');

const HERO_FRAME_COUNT=87;
const HERO_FRAME_PATH='assets/hero/frame_';
const heroFrames=new Array(HERO_FRAME_COUNT);
let heroFrameWidth=0;let heroFrameHeight=0;let heroCurrentFrame=-1;let heroLastDrawnWidth=0;let heroLastDrawnHeight=0;let heroLoaded=false;
function heroFrameUrl(index){return HERO_FRAME_PATH+String(index+1).padStart(4,'0')+'.webp';}
function resizeHeroCanvas(){if(!heroCanvas)return;const dpr=Math.min(window.devicePixelRatio||1,2);const width=Math.max(1,Math.round(heroCanvas.clientWidth*dpr));const height=Math.max(1,Math.round(heroCanvas.clientHeight*dpr));if(width===heroCanvas.width&&height===heroCanvas.height)return;heroCanvas.width=width;heroCanvas.height=height;heroLastDrawnWidth=0;heroLastDrawnHeight=0;if(heroCurrentFrame>=0)drawHeroFrame(heroCurrentFrame);}
function drawHeroFrame(index){if(!heroContext||!heroFrames[index])return;const image=heroFrames[index];const canvasWidth=heroCanvas.width;const canvasHeight=heroCanvas.height;if(!canvasWidth||!canvasHeight)return;heroContext.clearRect(0,0,canvasWidth,canvasHeight);const scale=Math.max(canvasWidth/image.naturalWidth,canvasHeight/image.naturalHeight);const drawWidth=image.naturalWidth*scale;const drawHeight=image.naturalHeight*scale;const x=(canvasWidth-drawWidth)/2;const y=(canvasHeight-drawHeight)/2;heroContext.drawImage(image,x,y,drawWidth,drawHeight);heroCurrentFrame=index;heroLastDrawnWidth=canvasWidth;heroLastDrawnHeight=canvasHeight;}
function setHeroFrame(index){if(!heroFrames.length)return;const clamped=clamp(index,0,HERO_FRAME_COUNT-1);if(heroFrames[clamped]){drawHeroFrame(clamped);return;}for(let offset=1;offset<HERO_FRAME_COUNT;offset++){const before=clamped-offset;const after=clamped+offset;if(before>=0&&heroFrames[before]){drawHeroFrame(before);return;}if(after<HERO_FRAME_COUNT&&heroFrames[after]){drawHeroFrame(after);return;}}}
function loadHeroFrame(index){return new Promise(resolve=>{const image=new Image();image.decoding='async';image.onload=()=>{heroFrames[index]=image;if(!heroFrameWidth){heroFrameWidth=image.naturalWidth;heroFrameHeight=image.naturalHeight;resizeHeroCanvas();}if(index===0){heroLoaded=true;hero?.classList.add('is-loaded');setHeroFrame(0);}resolve(image);};image.onerror=()=>resolve(null);image.src=heroFrameUrl(index);});}
async function loadHeroSequence(){if(!heroCanvas)return;resizeHeroCanvas();await loadHeroFrame(0);const batchSize=8;for(let start=1;start<HERO_FRAME_COUNT;start+=batchSize){const end=Math.min(HERO_FRAME_COUNT,start+batchSize);await Promise.all(Array.from({length:end-start},(_,offset)=>loadHeroFrame(start+offset)));}setHeroFrame(0);}window.addEventListener('resize',()=>{resizeHeroCanvas();updateHero();updateFacts();updateTransition();},{passive:true});loadHeroSequence();
const factsSection=$('#facts');const factCards=$$('.playing-card',factsSection).filter(card=>!card.classList.contains('playing-card--surprise'));const surpriseCard=$('#surpriseCard');const surpriseCardWrap=$('#surpriseCardWrap');const factsHint=$('#factsHint');let factsUnlockedAtScroll=null;factCards.forEach(card=>{card.addEventListener('click',()=>{card.classList.toggle('is-flipped');if(allFactsOpened()){factsUnlockedAtScroll=window.scrollY;}else{factsUnlockedAtScroll=null;}updateFacts();});});surpriseCard?.addEventListener('click',()=>{surpriseCard.classList.toggle('is-flipped');surpriseCardWrap?.classList.toggle('surprise-card--revealed',surpriseCard.classList.contains('is-flipped'));});function allFactsOpened(){return factCards.length===4&&factCards.every(card=>card.classList.contains('is-flipped'))}function updateFacts(){if(!factsSection)return;const opened=allFactsOpened();factsSection.classList.toggle('facts--unlocked',opened);if(opened){if(factsUnlockedAtScroll===null)factsUnlockedAtScroll=window.scrollY;const scrollAfterUnlock=Math.max(0,window.scrollY-factsUnlockedAtScroll);factsSection.classList.toggle('is-revealing',scrollAfterUnlock>=140);factsSection.classList.toggle('is-surprise',scrollAfterUnlock>=360);if(factsHint)factsHint.textContent='ПРОДОЛЖАЙТЕ СКРОЛЛИТЬ';}else{factsSection.classList.remove('is-revealing','is-surprise');factsUnlockedAtScroll=null;if(factsHint)factsHint.textContent='ОТКРОЙТЕ ВСЕ 4 КАРТЫ';}}
const transition=$('#transition');const kingZoom=$('#kingZoom');const transitionLabels=$('#eventLabels');function clamp(v,min,max){return Math.max(min,Math.min(max,v))}function lerp(a,b,t){return a+(b-a)*t}function sectionProgress(section){if(!section)return 0;const rect=section.getBoundingClientRect();const distance=section.offsetHeight-window.innerHeight;return clamp((-rect.top+window.innerHeight*0.18)/Math.max(1,distance),0,1);} function updateTransition(){if(!transition||!kingZoom)return;const p=sectionProgress(transition);const card=kingZoom.querySelector('.king-card');let maxZoom=4.5,baseWidth=1,baseHeight=1;if(card){baseWidth=Math.max(1,card.offsetWidth);baseHeight=Math.max(1,card.offsetHeight);}const reveal=1-Math.pow(1-p,3.6);const zoom=lerp(.01,maxZoom,reveal);const eyeX=baseWidth*.578,eyeY=baseHeight*.315,cardCenterX=baseWidth*.5,cardCenterY=baseHeight*.5;const offsetX=(cardCenterX-eyeX)*zoom,offsetY=(cardCenterY-eyeY)*zoom;kingZoom.style.transform='translate3d('+offsetX+'px,'+offsetY+'px,0) scale('+zoom+')';const kingIllustration=kingZoom.querySelector('.king-illustration');const kingBlur=clamp((.22-p)/.22,0,1);if(kingIllustration){kingIllustration.style.filter='brightness(.72) blur('+(kingBlur*18)+'px) drop-shadow(0 30px 90px rgba(0,0,0,.78))';}const labelsP=clamp((p-.72)/.22,0,1);transitionLabels.style.opacity=labelsP;transitionLabels.style.filter='blur('+(1-labelsP)*18+'px)';}
function updateHero(){const p=sectionProgress(hero);const title=$('[data-hero-title]');setHeroFrame(Math.round(p*(HERO_FRAME_COUNT-1)));if(title){title.style.opacity=p<.12?1:clamp((1-p)/.15,0,1);title.style.transform='translateY('+(p*45)+'px)';}}
function updateAll(){updateHero();updateFacts();updateTransition();}window.addEventListener('scroll',updateAll,{passive:true});updateAll();